title: New
author: Warrier Pranav
email: superpranavw@gmail.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
 This is my first content in a GitHub blog.Iam learning about pull requests 

# social links
twitter_username: notwitters
github_username:  warrierpranav

show_excerpts: true # set to false to remove excerpts on the homepage
